name: future_of_flutter_testing
description: Future of Flutter testing.
publish_to: "none"
version: 0.1.0

environment:
  flutter: ">=3.22.3 <4.0.0"
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  cross_file: ^0.3.3+8
  flutter:
    sdk: flutter
  flutter_deck: ^0.15.0
  fpdart: ^1.1.0
  get_it: ^7.6.4
  package_info_plus: ^8.0.2
  qr_flutter: ^4.1.0
  url_launcher: ^6.1.14

dev_dependencies:
  build_runner: ^2.4.6
  checks: ^0.3.0
  flutter_gen_runner: ^5.3.2
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  test: ^1.24.9
  very_good_analysis: ^6.0.0

flutter:
  assets:
    - assets/
  uses-material-design: true
